apiVersion: apps/v1
kind: Deployment
metadata:
  name: boundedcontext10121951219512196
  labels:
    app: boundedcontext10121951219512196
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boundedcontext10121951219512196
  template:
    metadata:
      labels:
        app: boundedcontext10121951219512196
    spec:
      containers:
        - name: boundedcontext10121951219512196
          image: "username/boundedcontext10121951219512196:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
